theme = "rose_pine"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.whitespace.render]
space = "none"
tab = "all"
tabpad = "all"
newline = "none"
nbsp = "all"

[editor.whitespace.characters]
space = " "
nbsp = "⍽"
tab = "→"
newline = "⏎"
tabpad = "·" # Tabs will look like "→···" (depending on tab width)

# [keys.insert.j]
# k = "normal_mode" # Maps `jk` to exit insert mode
